using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VoxelWorldEngine.Enums
{
    public enum BlockTextureMap
    {
        NULL,
        //ROW 1
        GRASS_TOP,
        STONE,
        DIRT,
        GRASS_SIDE,
        WOOD_TILES,
        STONE_PAVEMENT,
        IRON_BLOCK,
        BRICKS,
        TNT_SIDE,
        TNT_TOP,
        TNT_BOTTOM,
        SPIDER_NET_01,
        FLOWER_RED_01,
        FLOWER_YELLOW_01,
        MUD,
        SAPLING_OAK,
        BRICK_HALF,
        SANDSTONE_HALF,
        COBBLESTONE_HALF,

        ICON_BED,
        ICON_DOOR,
        ICON_WOOD_STONE,
        ICON_STAIR_WOOD_STONE,
        ICON_MULTYCOLOR,

        //ROW 2
        COBBLESTONE,
        BEDROCK,
        SAND,
        GRABEL,
        OAKTREE_SIDE,
        OAKTREE_TOP,
        IRON,
        GOLD,
        DIAMOND,
        EMERALD,
        REDSTONE,
        FORBBIDEN_SIGN,
        RED_MUSHROOM,
        BROWN_MUSHROOM,
        SAPLING_JUNGLE,
        SQUARE,
        STONE_BRICK_HALF,
        WOOD_TILES_HALF,
        STONE_PAVMENT_HALF,
        
        ICON_CAKE,
        IPHNO,
        FENCE_WOOD,
        FENCE_NETHER,
        NETHER_HALF,

        //ROW 3
        ORE_GOLD,
        ORE_IRON,
        ORE_COAL,
        BOOCK_SHELF,
        COOBLESTONE_OLD,
        OBSIDIAN,
        BLUE_CROSS,
        
        GRASS_DEAD,
        GRASS,
        REDSTONE_CORNER,
        LIGHT_DETECTOR_OFF,
        CRAFT_TABLE_TOP,
        FURNACE_OFF,
        FURNACE_SIDE,
        DISPENSER_FACE,
        DISPENSER_BACK,
        REDSTONE_TORCH_ON,
        REDSTONE_TORCH_OFF,
        COMUTATOR_1_ON,
        BUTTON,
        TORCH,
        LEVER,
        GEAR,
        COMUTATOR_2_ON,

        //ROW 4
        SPONGE,
        GLASS,
        ORE_DIAMOND,
        ORE_REDSTONE,
        LEAVES_OAK,
        LEAVES_JUNGLE,
        STONE_BRICKS,
        SAPLING_DEAD,
        SAPLING_PINE,
        LIGHTSENSOR_ON,
        LIGHTSENSOR_OFF,
        CRAFT_TABLE_SIDE_01,
        CRAFT_TABLE_SIDE_02,
        FURNACE_ON,
        FURNACE_BOTTOM,
        SAPLING_DARKOAK,
        FLOWER_RED_YELLOW,
        MUSHROOM_RED_BROWN,
        
        BLUE_LEAVES,
        FIRE_,
        FLOWER_PLANTED,
        LAVA,
        WATER,
        MUSHROOM_PLANTED,

        //ROW 5
        WHOOL_WHITE,
        SECTIONED_FACE,
        SNOW_TOP,
        ICE,
        GRASS_SIDE_SNOW,
        CACTUS_TOP,
        CATCUS_SIDE,
        CACTUS_CUTTED,
        STONE_FLATTEN, 
        SUGAR_CANNE,
        MUSIC_BOX_SIDE,
        MUSIC_BOX_TOP,
        NENUFER,
        GRASS_CORRUPTED_SIDE,
        GRASS_CORRUPTED_TOP,
        SAPLING_PRICH,
        PISTON_SIDE_01,
        PISTON_SIDE_02,
        PISTON_SIDE_03,
        PISTON_SIDE_04,
        RED_N_DIRT,
        SPIDER_NET_02,
        FLOWER_BLUE,
        REDSTONE_TRACK_CORNER,

        //ROW 6

    }
}
